spring.application.name=categoryService

server.port=5003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/categoryDb
spring.datasource.username=root
spring.datasource.password=Keshav@12